"""MLflow-enabled training entry point for the Yelp helpfulness model."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

import mlflow
import mlflow.sklearn
import yaml
from sklearn.linear_model import LogisticRegression

CONFIG_PATH = Path("src/config/config.yaml")


def load_config(config_path: Path = CONFIG_PATH) -> Dict[str, Any]:
    """Load the project configuration file."""
    with config_path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def train() -> None:
    """Run a placeholder MLflow training job."""
    config = load_config()
    training_cfg = config.get("training", {})
    hyperparams = training_cfg.get("hyperparameters", {})
    params = {
        "model_type": training_cfg.get("model_type", "logistic_regression"),
        "C": hyperparams.get("C", 1.0),
        "max_iter": hyperparams.get("max_iter", 1000),
        "class_weight": hyperparams.get("class_weight", "balanced"),
    }
    metrics = {"accuracy": 0.5, "f1": 0.5}
    model = LogisticRegression()

    models_cfg = config.get("models", {})
    artifacts_dir = Path(models_cfg.get("artifacts_dir", "models/artifacts"))
    registry_dir = Path(models_cfg.get("registry_dir", "models/registry"))
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    registry_dir.mkdir(parents=True, exist_ok=True)

    with mlflow.start_run(run_name="yelp_helpfulness_train") as run:
        for key, value in params.items():
            mlflow.log_param(key, value)
        mlflow.log_param("model_name", config.get("mlflow", {}).get("model_name", ""))
        for key, value in metrics.items():
            mlflow.log_metric(key, value)

        mlflow.sklearn.log_model(model, artifact_path="model")

        artifact_path = artifacts_dir / "training_placeholder.txt"
        artifact_path.write_text(
            "Placeholder artifact generated by the bootstrap training script.\n",
            encoding="utf-8",
        )
        mlflow.log_artifact(str(artifact_path))

        registry_placeholder = registry_dir / "latest_run.txt"
        registry_placeholder.write_text(
            f"Promoted run_id: {run.info.run_id}\n"
            f"Model name: {config.get('mlflow', {}).get('model_name', '')}\n",
            encoding="utf-8",
        )

    print("Training run logged to MLflow (placeholder).")


if __name__ == "__main__":
    train()
